window.SLIDER_ITEMS = [
    { id: "1", image: 'produkty/produkt-24.png', title: 'T-shirt Ultra light wzór 3', price: 99 },
    { id: "2", image: 'produkty/produkt-26.png', title: 'T-shirt Ultra light wzór 2', price: 99 },
    { id: "3", image: 'produkty/produkt-25.png', title: 'Longsleeve uniwersalny wzór 2', price: 149 },
    { id: "4", image: 'produkty/produkt-24.png', title: 'GKoszulka', price: 99 },
    { id: "4", image: 'produkty/produkt-37.png', title: 'GKoszulka', price: 99 },
    { id: "6", image: 'produkty/produkt-24.png', title: 'T-shirt Ultra light wzór 3', price: 99 },
    { id: "7", image: 'produkty/produkt-26.png', title: 'T-shirt Ultra light wzór 2', price: 99 },
    { id: "8", image: 'produkty/produkt-25.png', title: 'Longsleeve uniwersalny wzór 2', price: 149 },
    { id: "9", image: 'produkty/produkt-24.png', title: 'GKoszulka', price: 99 },
    { id: "10", image: 'produkty/produkt-24.png', title: 'GKoszulka', price: 99 },
    { id: "11", image: 'produkty/produkt-24.png', title: 'T-shirt Ultra light wzór 3', price: 99 },
    { id: "12", image: 'produkty/produkt-26.png', title: 'T-shirt Ultra light wzór 2', price: 99 },
    { id: "13", image: 'produkty/produkt-25.png', title: 'Longsleeve uniwersalny wzór 2', price: 149 },
    { id: "14", image: 'produkty/produkt-24.png', title: 'GKoszulka', price: 99 },
    { id: "15", image: 'produkty/produkt-24.png', title: 'GKoszulka', price: 99 },
    { id: "16", image: 'produkty/produkt-24.png', title: 'T-shirt Ultra light wzór 3', price: 99 },
    { id: "17", image: 'produkty/produkt-26.png', title: 'T-shirt Ultra light wzór 2', price: 99 },
    { id: "18", image: 'produkty/produkt-25.png', title: 'Longsleeve uniwersalny wzór 2', price: 149 },
    { id: "19", image: 'produkty/produkt-24.png', title: 'GKoszulka', price: 99 },
    { id: "20", image: 'produkty/produkt-24.png', title: 'GKoszulka', price: 99 },
  ];
  
